### ISSUE TITLE
Using the imwarp function

### ISSUE THREAD

**Issue by CejkaLuk** [aurooj/utility-matlab-functions#1]
Hi @aurooj ,

I'm sorry to post this in issues, but I don't quite understand how to use your imwarp function, could I ask for your help?
I was wondering if you could give a specific example which uses the imwarp function?

Parameters **I tried:**

imwarp( 'warpedImg.png' , 'F-original.png' , H , cornerPoints )

- **warpedImg.png** - blank 1152 x 648 image (If I understood correctly, this is the image that the warped image is going to be written on?)
- **F-original.png** - 400 x 320 image containing a grid pattern (This is the image that will be warped?)
- **H** - Homography matrix [1 0 0; 0 .5 0; 0 0 1] (Don't know if this has to be specific to the images or not, couldn't find detailed info on this, my apologies)
- **cornerPoints** - [0 0; 200 0; 200 100; 0 100] (I tried random points that would be located in the image, I couldn't get the meanPoints you mentioned to work)

I've attached the files I mentioned, if it helps in any way.
**warpedImg.png**
![warpedimg](https://user-images.githubusercontent.com/44003242/52537286-45f2d600-2d65-11e9-9de0-edd2c057aed5.png)
**F-original.png**
![f-original](https://user-images.githubusercontent.com/44003242/52537285-45f2d600-2d65-11e9-82e4-bc0220ccb577.png)

Could I please ask for your help?

If for any reason no, please tell me, and I'll close/delete this "issue".

Thank you in advance for responding.

**Comment by aurooj** [comment]
@CejkaLuk  You need to read both images before passing them to the function. 
mean_points are nothing but four (x,y) points within which the image will be embed after warping applied using homography matrix. 

This code was written in matlab 2012 version, so you will need to check if it's not compatible with the recent versions.

**Comment by CejkaLuk** [comment]
Will try that, thank you for taking the time to explain.
